//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 11.0.50727.1
// 
namespace Murta.OrdemServico.UI.Windows8.SistemaServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OS", Namespace="http://schemas.datacontract.org/2004/07/Murta.OrdemServico.Dto")]
    public partial class OS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string AtividadeField;
        
        private Murta.OrdemServico.UI.Windows8.SistemaServiceReference.Cliente ClienteField;
        
        private int CodigoField;
        
        private System.DateTime DataField;
        
        private Murta.OrdemServico.UI.Windows8.SistemaServiceReference.Empresa EmpresaField;
        
        private string FaturadoField;
        
        private Murta.OrdemServico.UI.Windows8.SistemaServiceReference.Filial FilialField;
        
        private string FimField;
        
        private Murta.OrdemServico.UI.Windows8.SistemaServiceReference.Funcionario FuncionarioField;
        
        private string InicioField;
        
        private string ObservacaoField;
        
        private Murta.OrdemServico.UI.Windows8.SistemaServiceReference.Projeto ProjetoField;
        
        private Murta.OrdemServico.UI.Windows8.SistemaServiceReference.Status StatusField;
        
        private Murta.OrdemServico.UI.Windows8.SistemaServiceReference.TipoHora TipoHoraField;
        
        private string TrasladoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Atividade {
            get {
                return this.AtividadeField;
            }
            set {
                if ((object.ReferenceEquals(this.AtividadeField, value) != true)) {
                    this.AtividadeField = value;
                    this.RaisePropertyChanged("Atividade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Murta.OrdemServico.UI.Windows8.SistemaServiceReference.Cliente Cliente {
            get {
                return this.ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteField, value) != true)) {
                    this.ClienteField = value;
                    this.RaisePropertyChanged("Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Murta.OrdemServico.UI.Windows8.SistemaServiceReference.Empresa Empresa {
            get {
                return this.EmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpresaField, value) != true)) {
                    this.EmpresaField = value;
                    this.RaisePropertyChanged("Empresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Faturado {
            get {
                return this.FaturadoField;
            }
            set {
                if ((object.ReferenceEquals(this.FaturadoField, value) != true)) {
                    this.FaturadoField = value;
                    this.RaisePropertyChanged("Faturado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Murta.OrdemServico.UI.Windows8.SistemaServiceReference.Filial Filial {
            get {
                return this.FilialField;
            }
            set {
                if ((object.ReferenceEquals(this.FilialField, value) != true)) {
                    this.FilialField = value;
                    this.RaisePropertyChanged("Filial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fim {
            get {
                return this.FimField;
            }
            set {
                if ((object.ReferenceEquals(this.FimField, value) != true)) {
                    this.FimField = value;
                    this.RaisePropertyChanged("Fim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Murta.OrdemServico.UI.Windows8.SistemaServiceReference.Funcionario Funcionario {
            get {
                return this.FuncionarioField;
            }
            set {
                if ((object.ReferenceEquals(this.FuncionarioField, value) != true)) {
                    this.FuncionarioField = value;
                    this.RaisePropertyChanged("Funcionario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Inicio {
            get {
                return this.InicioField;
            }
            set {
                if ((object.ReferenceEquals(this.InicioField, value) != true)) {
                    this.InicioField = value;
                    this.RaisePropertyChanged("Inicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observacao {
            get {
                return this.ObservacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacaoField, value) != true)) {
                    this.ObservacaoField = value;
                    this.RaisePropertyChanged("Observacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Murta.OrdemServico.UI.Windows8.SistemaServiceReference.Projeto Projeto {
            get {
                return this.ProjetoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjetoField, value) != true)) {
                    this.ProjetoField = value;
                    this.RaisePropertyChanged("Projeto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Murta.OrdemServico.UI.Windows8.SistemaServiceReference.Status Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Murta.OrdemServico.UI.Windows8.SistemaServiceReference.TipoHora TipoHora {
            get {
                return this.TipoHoraField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoHoraField, value) != true)) {
                    this.TipoHoraField = value;
                    this.RaisePropertyChanged("TipoHora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Traslado {
            get {
                return this.TrasladoField;
            }
            set {
                if ((object.ReferenceEquals(this.TrasladoField, value) != true)) {
                    this.TrasladoField = value;
                    this.RaisePropertyChanged("Traslado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/Murta.OrdemServico.Dto")]
    public partial class Cliente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int CodigoField;
        
        private string NomeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empresa", Namespace="http://schemas.datacontract.org/2004/07/Murta.OrdemServico.Dto")]
    public partial class Empresa : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string CodigoField;
        
        private string NomeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Filial", Namespace="http://schemas.datacontract.org/2004/07/Murta.OrdemServico.Dto")]
    public partial class Filial : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string CodigoField;
        
        private string ReduzidoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reduzido {
            get {
                return this.ReduzidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ReduzidoField, value) != true)) {
                    this.ReduzidoField = value;
                    this.RaisePropertyChanged("Reduzido");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Funcionario", Namespace="http://schemas.datacontract.org/2004/07/Murta.OrdemServico.Dto")]
    public partial class Funcionario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int CodigoField;
        
        private string NomeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Projeto", Namespace="http://schemas.datacontract.org/2004/07/Murta.OrdemServico.Dto")]
    public partial class Projeto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int CodigoField;
        
        private string DescricaoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Status", Namespace="http://schemas.datacontract.org/2004/07/Murta.OrdemServico.Dto")]
    public partial class Status : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int CodigoField;
        
        private string DescricaoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoHora", Namespace="http://schemas.datacontract.org/2004/07/Murta.OrdemServico.Dto")]
    public partial class TipoHora : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int CodigoField;
        
        private string DescricaoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoData", Namespace="http://schemas.datacontract.org/2004/07/Murta.OrdemServico.Service.WCF.Enums")]
    public enum TipoData : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataDe = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataAte = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SistemaServiceReference.ISistema")]
    public interface ISistema {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistema/CadastrarOrdemServico", ReplyAction="http://tempuri.org/ISistema/CadastrarOrdemServicoResponse")]
        System.Threading.Tasks.Task CadastrarOrdemServicoAsync(Murta.OrdemServico.UI.Windows8.SistemaServiceReference.OS ordemServico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistema/EditarOrdemServico", ReplyAction="http://tempuri.org/ISistema/EditarOrdemServicoResponse")]
        System.Threading.Tasks.Task EditarOrdemServicoAsync(Murta.OrdemServico.UI.Windows8.SistemaServiceReference.OS ordemServico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistema/ExcluirOrdemServico", ReplyAction="http://tempuri.org/ISistema/ExcluirOrdemServicoResponse")]
        System.Threading.Tasks.Task ExcluirOrdemServicoAsync(Murta.OrdemServico.UI.Windows8.SistemaServiceReference.OS ordemServico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistema/ConsultarOrdemServico", ReplyAction="http://tempuri.org/ISistema/ConsultarOrdemServicoResponse")]
        System.Threading.Tasks.Task<Murta.OrdemServico.UI.Windows8.SistemaServiceReference.OS> ConsultarOrdemServicoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistema/ListarOrdemServico", ReplyAction="http://tempuri.org/ISistema/ListarOrdemServicoResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Murta.OrdemServico.UI.Windows8.SistemaServiceReference.OS>> ListarOrdemServicoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistema/ListarPorRangeDataOrdemServico", ReplyAction="http://tempuri.org/ISistema/ListarPorRangeDataOrdemServicoResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Murta.OrdemServico.UI.Windows8.SistemaServiceReference.OS>> ListarPorRangeDataOrdemServicoAsync(System.DateTime dataDe, System.DateTime dataAte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistema/ListarPorRangedeDataeFuncionarioOrdemServico", ReplyAction="http://tempuri.org/ISistema/ListarPorRangedeDataeFuncionarioOrdemServicoResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Murta.OrdemServico.UI.Windows8.SistemaServiceReference.OS>> ListarPorRangedeDataeFuncionarioOrdemServicoAsync(System.DateTime dataDe, System.DateTime dataAte, Murta.OrdemServico.UI.Windows8.SistemaServiceReference.Funcionario funcionario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistema/ListarPorRangedeDataeClienteOrdemServico", ReplyAction="http://tempuri.org/ISistema/ListarPorRangedeDataeClienteOrdemServicoResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Murta.OrdemServico.UI.Windows8.SistemaServiceReference.OS>> ListarPorRangedeDataeClienteOrdemServicoAsync(System.DateTime dataDe, System.DateTime dataAte, Murta.OrdemServico.UI.Windows8.SistemaServiceReference.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistema/ListarPorRangedeDataeFuncionarioeClienteOrdemServico", ReplyAction="http://tempuri.org/ISistema/ListarPorRangedeDataeFuncionarioeClienteOrdemServicoR" +
            "esponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Murta.OrdemServico.UI.Windows8.SistemaServiceReference.OS>> ListarPorRangedeDataeFuncionarioeClienteOrdemServicoAsync(System.DateTime dataDe, System.DateTime dataAte, Murta.OrdemServico.UI.Windows8.SistemaServiceReference.Cliente cliente, Murta.OrdemServico.UI.Windows8.SistemaServiceReference.Funcionario funcionario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistema/ListarPorDataeFuncionarioOrdemServico", ReplyAction="http://tempuri.org/ISistema/ListarPorDataeFuncionarioOrdemServicoResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Murta.OrdemServico.UI.Windows8.SistemaServiceReference.OS>> ListarPorDataeFuncionarioOrdemServicoAsync(System.DateTime data, Murta.OrdemServico.UI.Windows8.SistemaServiceReference.Funcionario funcionario, Murta.OrdemServico.UI.Windows8.SistemaServiceReference.TipoData tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistema/ListarPorDataeClienteOrdemServico", ReplyAction="http://tempuri.org/ISistema/ListarPorDataeClienteOrdemServicoResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Murta.OrdemServico.UI.Windows8.SistemaServiceReference.OS>> ListarPorDataeClienteOrdemServicoAsync(System.DateTime data, Murta.OrdemServico.UI.Windows8.SistemaServiceReference.Cliente cliente, Murta.OrdemServico.UI.Windows8.SistemaServiceReference.TipoData tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistema/ListarPorDataeFuncionarioeClienteOrdemServico", ReplyAction="http://tempuri.org/ISistema/ListarPorDataeFuncionarioeClienteOrdemServicoResponse" +
            "")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Murta.OrdemServico.UI.Windows8.SistemaServiceReference.OS>> ListarPorDataeFuncionarioeClienteOrdemServicoAsync(System.DateTime data, Murta.OrdemServico.UI.Windows8.SistemaServiceReference.Funcionario funcionario, Murta.OrdemServico.UI.Windows8.SistemaServiceReference.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistema/ListarPorDataOrdemServico", ReplyAction="http://tempuri.org/ISistema/ListarPorDataOrdemServicoResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Murta.OrdemServico.UI.Windows8.SistemaServiceReference.OS>> ListarPorDataOrdemServicoAsync(System.DateTime data, Murta.OrdemServico.UI.Windows8.SistemaServiceReference.TipoData tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistema/ListarPorFuncionarioeClienteOrdemServico", ReplyAction="http://tempuri.org/ISistema/ListarPorFuncionarioeClienteOrdemServicoResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Murta.OrdemServico.UI.Windows8.SistemaServiceReference.OS>> ListarPorFuncionarioeClienteOrdemServicoAsync(Murta.OrdemServico.UI.Windows8.SistemaServiceReference.Funcionario funcionario, Murta.OrdemServico.UI.Windows8.SistemaServiceReference.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistema/ListarPorFuncionarioOrdemServico", ReplyAction="http://tempuri.org/ISistema/ListarPorFuncionarioOrdemServicoResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Murta.OrdemServico.UI.Windows8.SistemaServiceReference.OS>> ListarPorFuncionarioOrdemServicoAsync(Murta.OrdemServico.UI.Windows8.SistemaServiceReference.Funcionario funcionario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistema/ListarPorClienteOrdemServico", ReplyAction="http://tempuri.org/ISistema/ListarPorClienteOrdemServicoResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Murta.OrdemServico.UI.Windows8.SistemaServiceReference.OS>> ListarPorClienteOrdemServicoAsync(Murta.OrdemServico.UI.Windows8.SistemaServiceReference.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistema/ListarClientes", ReplyAction="http://tempuri.org/ISistema/ListarClientesResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Murta.OrdemServico.UI.Windows8.SistemaServiceReference.Cliente>> ListarClientesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistema/ListarProjetos", ReplyAction="http://tempuri.org/ISistema/ListarProjetosResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Murta.OrdemServico.UI.Windows8.SistemaServiceReference.Projeto>> ListarProjetosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistema/ListarTiposHora", ReplyAction="http://tempuri.org/ISistema/ListarTiposHoraResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Murta.OrdemServico.UI.Windows8.SistemaServiceReference.TipoHora>> ListarTiposHoraAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistema/ListarFuncionarios", ReplyAction="http://tempuri.org/ISistema/ListarFuncionariosResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Murta.OrdemServico.UI.Windows8.SistemaServiceReference.Funcionario>> ListarFuncionariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistema/ListarStatus", ReplyAction="http://tempuri.org/ISistema/ListarStatusResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Murta.OrdemServico.UI.Windows8.SistemaServiceReference.Status>> ListarStatusAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISistemaChannel : Murta.OrdemServico.UI.Windows8.SistemaServiceReference.ISistema, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SistemaClient : System.ServiceModel.ClientBase<Murta.OrdemServico.UI.Windows8.SistemaServiceReference.ISistema>, Murta.OrdemServico.UI.Windows8.SistemaServiceReference.ISistema {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SistemaClient() : 
                base(SistemaClient.GetDefaultBinding(), SistemaClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ISistema.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SistemaClient(EndpointConfiguration endpointConfiguration) : 
                base(SistemaClient.GetBindingForEndpoint(endpointConfiguration), SistemaClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SistemaClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SistemaClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SistemaClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SistemaClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SistemaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task CadastrarOrdemServicoAsync(Murta.OrdemServico.UI.Windows8.SistemaServiceReference.OS ordemServico) {
            return base.Channel.CadastrarOrdemServicoAsync(ordemServico);
        }
        
        public System.Threading.Tasks.Task EditarOrdemServicoAsync(Murta.OrdemServico.UI.Windows8.SistemaServiceReference.OS ordemServico) {
            return base.Channel.EditarOrdemServicoAsync(ordemServico);
        }
        
        public System.Threading.Tasks.Task ExcluirOrdemServicoAsync(Murta.OrdemServico.UI.Windows8.SistemaServiceReference.OS ordemServico) {
            return base.Channel.ExcluirOrdemServicoAsync(ordemServico);
        }
        
        public System.Threading.Tasks.Task<Murta.OrdemServico.UI.Windows8.SistemaServiceReference.OS> ConsultarOrdemServicoAsync(int id) {
            return base.Channel.ConsultarOrdemServicoAsync(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Murta.OrdemServico.UI.Windows8.SistemaServiceReference.OS>> ListarOrdemServicoAsync() {
            return base.Channel.ListarOrdemServicoAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Murta.OrdemServico.UI.Windows8.SistemaServiceReference.OS>> ListarPorRangeDataOrdemServicoAsync(System.DateTime dataDe, System.DateTime dataAte) {
            return base.Channel.ListarPorRangeDataOrdemServicoAsync(dataDe, dataAte);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Murta.OrdemServico.UI.Windows8.SistemaServiceReference.OS>> ListarPorRangedeDataeFuncionarioOrdemServicoAsync(System.DateTime dataDe, System.DateTime dataAte, Murta.OrdemServico.UI.Windows8.SistemaServiceReference.Funcionario funcionario) {
            return base.Channel.ListarPorRangedeDataeFuncionarioOrdemServicoAsync(dataDe, dataAte, funcionario);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Murta.OrdemServico.UI.Windows8.SistemaServiceReference.OS>> ListarPorRangedeDataeClienteOrdemServicoAsync(System.DateTime dataDe, System.DateTime dataAte, Murta.OrdemServico.UI.Windows8.SistemaServiceReference.Cliente cliente) {
            return base.Channel.ListarPorRangedeDataeClienteOrdemServicoAsync(dataDe, dataAte, cliente);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Murta.OrdemServico.UI.Windows8.SistemaServiceReference.OS>> ListarPorRangedeDataeFuncionarioeClienteOrdemServicoAsync(System.DateTime dataDe, System.DateTime dataAte, Murta.OrdemServico.UI.Windows8.SistemaServiceReference.Cliente cliente, Murta.OrdemServico.UI.Windows8.SistemaServiceReference.Funcionario funcionario) {
            return base.Channel.ListarPorRangedeDataeFuncionarioeClienteOrdemServicoAsync(dataDe, dataAte, cliente, funcionario);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Murta.OrdemServico.UI.Windows8.SistemaServiceReference.OS>> ListarPorDataeFuncionarioOrdemServicoAsync(System.DateTime data, Murta.OrdemServico.UI.Windows8.SistemaServiceReference.Funcionario funcionario, Murta.OrdemServico.UI.Windows8.SistemaServiceReference.TipoData tipo) {
            return base.Channel.ListarPorDataeFuncionarioOrdemServicoAsync(data, funcionario, tipo);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Murta.OrdemServico.UI.Windows8.SistemaServiceReference.OS>> ListarPorDataeClienteOrdemServicoAsync(System.DateTime data, Murta.OrdemServico.UI.Windows8.SistemaServiceReference.Cliente cliente, Murta.OrdemServico.UI.Windows8.SistemaServiceReference.TipoData tipo) {
            return base.Channel.ListarPorDataeClienteOrdemServicoAsync(data, cliente, tipo);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Murta.OrdemServico.UI.Windows8.SistemaServiceReference.OS>> ListarPorDataeFuncionarioeClienteOrdemServicoAsync(System.DateTime data, Murta.OrdemServico.UI.Windows8.SistemaServiceReference.Funcionario funcionario, Murta.OrdemServico.UI.Windows8.SistemaServiceReference.Cliente cliente) {
            return base.Channel.ListarPorDataeFuncionarioeClienteOrdemServicoAsync(data, funcionario, cliente);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Murta.OrdemServico.UI.Windows8.SistemaServiceReference.OS>> ListarPorDataOrdemServicoAsync(System.DateTime data, Murta.OrdemServico.UI.Windows8.SistemaServiceReference.TipoData tipo) {
            return base.Channel.ListarPorDataOrdemServicoAsync(data, tipo);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Murta.OrdemServico.UI.Windows8.SistemaServiceReference.OS>> ListarPorFuncionarioeClienteOrdemServicoAsync(Murta.OrdemServico.UI.Windows8.SistemaServiceReference.Funcionario funcionario, Murta.OrdemServico.UI.Windows8.SistemaServiceReference.Cliente cliente) {
            return base.Channel.ListarPorFuncionarioeClienteOrdemServicoAsync(funcionario, cliente);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Murta.OrdemServico.UI.Windows8.SistemaServiceReference.OS>> ListarPorFuncionarioOrdemServicoAsync(Murta.OrdemServico.UI.Windows8.SistemaServiceReference.Funcionario funcionario) {
            return base.Channel.ListarPorFuncionarioOrdemServicoAsync(funcionario);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Murta.OrdemServico.UI.Windows8.SistemaServiceReference.OS>> ListarPorClienteOrdemServicoAsync(Murta.OrdemServico.UI.Windows8.SistemaServiceReference.Cliente cliente) {
            return base.Channel.ListarPorClienteOrdemServicoAsync(cliente);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Murta.OrdemServico.UI.Windows8.SistemaServiceReference.Cliente>> ListarClientesAsync() {
            return base.Channel.ListarClientesAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Murta.OrdemServico.UI.Windows8.SistemaServiceReference.Projeto>> ListarProjetosAsync() {
            return base.Channel.ListarProjetosAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Murta.OrdemServico.UI.Windows8.SistemaServiceReference.TipoHora>> ListarTiposHoraAsync() {
            return base.Channel.ListarTiposHoraAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Murta.OrdemServico.UI.Windows8.SistemaServiceReference.Funcionario>> ListarFuncionariosAsync() {
            return base.Channel.ListarFuncionariosAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Murta.OrdemServico.UI.Windows8.SistemaServiceReference.Status>> ListarStatusAsync() {
            return base.Channel.ListarStatusAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISistema)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISistema)) {
                return new System.ServiceModel.EndpointAddress("http://localhost:57837/SistemaService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return SistemaClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ISistema);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return SistemaClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ISistema);
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_ISistema,
        }
    }
}
