//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Murta.OrdemServico.UI.Web.WebForms.OrdemServico {
    
    
    public partial class Editar {
        
        /// <summary>
        /// Formulario1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Murta.OrdemServico.UI.Web.WebForms.OrdemServico.UserControls.Formulario Formulario1;
    }
}
