//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OS", Namespace="http://schemas.datacontract.org/2004/07/Murta.OrdemServico.Dto")]
    [System.SerializableAttribute()]
    public partial class OS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AtividadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.Cliente ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.Empresa EmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaturadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.Filial FilialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FimField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.Funcionario FuncionarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.Projeto ProjetoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.Status StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.TipoHora TipoHoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrasladoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Atividade {
            get {
                return this.AtividadeField;
            }
            set {
                if ((object.ReferenceEquals(this.AtividadeField, value) != true)) {
                    this.AtividadeField = value;
                    this.RaisePropertyChanged("Atividade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.Cliente Cliente {
            get {
                return this.ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteField, value) != true)) {
                    this.ClienteField = value;
                    this.RaisePropertyChanged("Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.Empresa Empresa {
            get {
                return this.EmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpresaField, value) != true)) {
                    this.EmpresaField = value;
                    this.RaisePropertyChanged("Empresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Faturado {
            get {
                return this.FaturadoField;
            }
            set {
                if ((object.ReferenceEquals(this.FaturadoField, value) != true)) {
                    this.FaturadoField = value;
                    this.RaisePropertyChanged("Faturado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.Filial Filial {
            get {
                return this.FilialField;
            }
            set {
                if ((object.ReferenceEquals(this.FilialField, value) != true)) {
                    this.FilialField = value;
                    this.RaisePropertyChanged("Filial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fim {
            get {
                return this.FimField;
            }
            set {
                if ((object.ReferenceEquals(this.FimField, value) != true)) {
                    this.FimField = value;
                    this.RaisePropertyChanged("Fim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.Funcionario Funcionario {
            get {
                return this.FuncionarioField;
            }
            set {
                if ((object.ReferenceEquals(this.FuncionarioField, value) != true)) {
                    this.FuncionarioField = value;
                    this.RaisePropertyChanged("Funcionario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Inicio {
            get {
                return this.InicioField;
            }
            set {
                if ((object.ReferenceEquals(this.InicioField, value) != true)) {
                    this.InicioField = value;
                    this.RaisePropertyChanged("Inicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observacao {
            get {
                return this.ObservacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacaoField, value) != true)) {
                    this.ObservacaoField = value;
                    this.RaisePropertyChanged("Observacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.Projeto Projeto {
            get {
                return this.ProjetoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjetoField, value) != true)) {
                    this.ProjetoField = value;
                    this.RaisePropertyChanged("Projeto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.Status Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.TipoHora TipoHora {
            get {
                return this.TipoHoraField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoHoraField, value) != true)) {
                    this.TipoHoraField = value;
                    this.RaisePropertyChanged("TipoHora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Traslado {
            get {
                return this.TrasladoField;
            }
            set {
                if ((object.ReferenceEquals(this.TrasladoField, value) != true)) {
                    this.TrasladoField = value;
                    this.RaisePropertyChanged("Traslado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/Murta.OrdemServico.Dto")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empresa", Namespace="http://schemas.datacontract.org/2004/07/Murta.OrdemServico.Dto")]
    [System.SerializableAttribute()]
    public partial class Empresa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Filial", Namespace="http://schemas.datacontract.org/2004/07/Murta.OrdemServico.Dto")]
    [System.SerializableAttribute()]
    public partial class Filial : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReduzidoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reduzido {
            get {
                return this.ReduzidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ReduzidoField, value) != true)) {
                    this.ReduzidoField = value;
                    this.RaisePropertyChanged("Reduzido");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Funcionario", Namespace="http://schemas.datacontract.org/2004/07/Murta.OrdemServico.Dto")]
    [System.SerializableAttribute()]
    public partial class Funcionario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Projeto", Namespace="http://schemas.datacontract.org/2004/07/Murta.OrdemServico.Dto")]
    [System.SerializableAttribute()]
    public partial class Projeto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Status", Namespace="http://schemas.datacontract.org/2004/07/Murta.OrdemServico.Dto")]
    [System.SerializableAttribute()]
    public partial class Status : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoHora", Namespace="http://schemas.datacontract.org/2004/07/Murta.OrdemServico.Dto")]
    [System.SerializableAttribute()]
    public partial class TipoHora : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoData", Namespace="http://schemas.datacontract.org/2004/07/Murta.OrdemServico.Service.WCF.Enums")]
    public enum TipoData : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataDe = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataAte = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SistemaServiceReference.ISistema")]
    public interface ISistema {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistema/CadastrarOrdemServico", ReplyAction="http://tempuri.org/ISistema/CadastrarOrdemServicoResponse")]
        void CadastrarOrdemServico(Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.OS ordemServico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistema/EditarOrdemServico", ReplyAction="http://tempuri.org/ISistema/EditarOrdemServicoResponse")]
        void EditarOrdemServico(Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.OS ordemServico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistema/ExcluirOrdemServico", ReplyAction="http://tempuri.org/ISistema/ExcluirOrdemServicoResponse")]
        void ExcluirOrdemServico(Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.OS ordemServico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistema/ConsultarOrdemServico", ReplyAction="http://tempuri.org/ISistema/ConsultarOrdemServicoResponse")]
        Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.OS ConsultarOrdemServico(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistema/ListarOrdemServico", ReplyAction="http://tempuri.org/ISistema/ListarOrdemServicoResponse")]
        Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.OS[] ListarOrdemServico();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistema/ListarPorRangeDataOrdemServico", ReplyAction="http://tempuri.org/ISistema/ListarPorRangeDataOrdemServicoResponse")]
        Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.OS[] ListarPorRangeDataOrdemServico(System.DateTime dataDe, System.DateTime dataAte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistema/ListarPorRangedeDataeFuncionarioOrdemServico", ReplyAction="http://tempuri.org/ISistema/ListarPorRangedeDataeFuncionarioOrdemServicoResponse")]
        Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.OS[] ListarPorRangedeDataeFuncionarioOrdemServico(System.DateTime dataDe, System.DateTime dataAte, Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.Funcionario funcionario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistema/ListarPorRangedeDataeClienteOrdemServico", ReplyAction="http://tempuri.org/ISistema/ListarPorRangedeDataeClienteOrdemServicoResponse")]
        Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.OS[] ListarPorRangedeDataeClienteOrdemServico(System.DateTime dataDe, System.DateTime dataAte, Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistema/ListarPorRangedeDataeFuncionarioeClienteOrdemServico", ReplyAction="http://tempuri.org/ISistema/ListarPorRangedeDataeFuncionarioeClienteOrdemServicoR" +
            "esponse")]
        Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.OS[] ListarPorRangedeDataeFuncionarioeClienteOrdemServico(System.DateTime dataDe, System.DateTime dataAte, Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.Cliente cliente, Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.Funcionario funcionario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistema/ListarPorDataeFuncionarioOrdemServico", ReplyAction="http://tempuri.org/ISistema/ListarPorDataeFuncionarioOrdemServicoResponse")]
        Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.OS[] ListarPorDataeFuncionarioOrdemServico(System.DateTime data, Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.Funcionario funcionario, Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.TipoData tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistema/ListarPorDataeClienteOrdemServico", ReplyAction="http://tempuri.org/ISistema/ListarPorDataeClienteOrdemServicoResponse")]
        Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.OS[] ListarPorDataeClienteOrdemServico(System.DateTime data, Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.Cliente cliente, Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.TipoData tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistema/ListarPorDataeFuncionarioeClienteOrdemServico", ReplyAction="http://tempuri.org/ISistema/ListarPorDataeFuncionarioeClienteOrdemServicoResponse" +
            "")]
        Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.OS[] ListarPorDataeFuncionarioeClienteOrdemServico(System.DateTime data, Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.Funcionario funcionario, Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistema/ListarPorDataOrdemServico", ReplyAction="http://tempuri.org/ISistema/ListarPorDataOrdemServicoResponse")]
        Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.OS[] ListarPorDataOrdemServico(System.DateTime data, Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.TipoData tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistema/ListarPorFuncionarioeClienteOrdemServico", ReplyAction="http://tempuri.org/ISistema/ListarPorFuncionarioeClienteOrdemServicoResponse")]
        Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.OS[] ListarPorFuncionarioeClienteOrdemServico(Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.Funcionario funcionario, Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistema/ListarPorFuncionarioOrdemServico", ReplyAction="http://tempuri.org/ISistema/ListarPorFuncionarioOrdemServicoResponse")]
        Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.OS[] ListarPorFuncionarioOrdemServico(Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.Funcionario funcionario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistema/ListarPorClienteOrdemServico", ReplyAction="http://tempuri.org/ISistema/ListarPorClienteOrdemServicoResponse")]
        Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.OS[] ListarPorClienteOrdemServico(Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistema/ListarClientes", ReplyAction="http://tempuri.org/ISistema/ListarClientesResponse")]
        Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.Cliente[] ListarClientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistema/ListarProjetos", ReplyAction="http://tempuri.org/ISistema/ListarProjetosResponse")]
        Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.Projeto[] ListarProjetos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistema/ListarTiposHora", ReplyAction="http://tempuri.org/ISistema/ListarTiposHoraResponse")]
        Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.TipoHora[] ListarTiposHora();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistema/ListarFuncionarios", ReplyAction="http://tempuri.org/ISistema/ListarFuncionariosResponse")]
        Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.Funcionario[] ListarFuncionarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistema/ListarStatus", ReplyAction="http://tempuri.org/ISistema/ListarStatusResponse")]
        Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.Status[] ListarStatus();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISistemaChannel : Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.ISistema, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SistemaClient : System.ServiceModel.ClientBase<Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.ISistema>, Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.ISistema {
        
        public SistemaClient() {
        }
        
        public SistemaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SistemaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SistemaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SistemaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CadastrarOrdemServico(Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.OS ordemServico) {
            base.Channel.CadastrarOrdemServico(ordemServico);
        }
        
        public void EditarOrdemServico(Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.OS ordemServico) {
            base.Channel.EditarOrdemServico(ordemServico);
        }
        
        public void ExcluirOrdemServico(Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.OS ordemServico) {
            base.Channel.ExcluirOrdemServico(ordemServico);
        }
        
        public Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.OS ConsultarOrdemServico(int id) {
            return base.Channel.ConsultarOrdemServico(id);
        }
        
        public Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.OS[] ListarOrdemServico() {
            return base.Channel.ListarOrdemServico();
        }
        
        public Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.OS[] ListarPorRangeDataOrdemServico(System.DateTime dataDe, System.DateTime dataAte) {
            return base.Channel.ListarPorRangeDataOrdemServico(dataDe, dataAte);
        }
        
        public Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.OS[] ListarPorRangedeDataeFuncionarioOrdemServico(System.DateTime dataDe, System.DateTime dataAte, Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.Funcionario funcionario) {
            return base.Channel.ListarPorRangedeDataeFuncionarioOrdemServico(dataDe, dataAte, funcionario);
        }
        
        public Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.OS[] ListarPorRangedeDataeClienteOrdemServico(System.DateTime dataDe, System.DateTime dataAte, Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.Cliente cliente) {
            return base.Channel.ListarPorRangedeDataeClienteOrdemServico(dataDe, dataAte, cliente);
        }
        
        public Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.OS[] ListarPorRangedeDataeFuncionarioeClienteOrdemServico(System.DateTime dataDe, System.DateTime dataAte, Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.Cliente cliente, Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.Funcionario funcionario) {
            return base.Channel.ListarPorRangedeDataeFuncionarioeClienteOrdemServico(dataDe, dataAte, cliente, funcionario);
        }
        
        public Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.OS[] ListarPorDataeFuncionarioOrdemServico(System.DateTime data, Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.Funcionario funcionario, Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.TipoData tipo) {
            return base.Channel.ListarPorDataeFuncionarioOrdemServico(data, funcionario, tipo);
        }
        
        public Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.OS[] ListarPorDataeClienteOrdemServico(System.DateTime data, Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.Cliente cliente, Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.TipoData tipo) {
            return base.Channel.ListarPorDataeClienteOrdemServico(data, cliente, tipo);
        }
        
        public Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.OS[] ListarPorDataeFuncionarioeClienteOrdemServico(System.DateTime data, Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.Funcionario funcionario, Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.Cliente cliente) {
            return base.Channel.ListarPorDataeFuncionarioeClienteOrdemServico(data, funcionario, cliente);
        }
        
        public Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.OS[] ListarPorDataOrdemServico(System.DateTime data, Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.TipoData tipo) {
            return base.Channel.ListarPorDataOrdemServico(data, tipo);
        }
        
        public Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.OS[] ListarPorFuncionarioeClienteOrdemServico(Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.Funcionario funcionario, Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.Cliente cliente) {
            return base.Channel.ListarPorFuncionarioeClienteOrdemServico(funcionario, cliente);
        }
        
        public Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.OS[] ListarPorFuncionarioOrdemServico(Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.Funcionario funcionario) {
            return base.Channel.ListarPorFuncionarioOrdemServico(funcionario);
        }
        
        public Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.OS[] ListarPorClienteOrdemServico(Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.Cliente cliente) {
            return base.Channel.ListarPorClienteOrdemServico(cliente);
        }
        
        public Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.Cliente[] ListarClientes() {
            return base.Channel.ListarClientes();
        }
        
        public Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.Projeto[] ListarProjetos() {
            return base.Channel.ListarProjetos();
        }
        
        public Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.TipoHora[] ListarTiposHora() {
            return base.Channel.ListarTiposHora();
        }
        
        public Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.Funcionario[] ListarFuncionarios() {
            return base.Channel.ListarFuncionarios();
        }
        
        public Murta.OrdemServico.UI.Web.WebForms.SistemaServiceReference.Status[] ListarStatus() {
            return base.Channel.ListarStatus();
        }
    }
}
