'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace SistemaServiceReference
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="OS", [Namespace]:="http://schemas.datacontract.org/2004/07/Murta.OrdemServico.Dto"),  _
     System.SerializableAttribute()>  _
    Partial Public Class OS
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AtividadeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClienteField As SistemaServiceReference.Cliente
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodigoField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DataField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmpresaField As SistemaServiceReference.Empresa
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FaturadoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FilialField As SistemaServiceReference.Filial
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FimField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FuncionarioField As SistemaServiceReference.Funcionario
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private InicioField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ObservacaoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ProjetoField As SistemaServiceReference.Projeto
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StatusField As SistemaServiceReference.Status
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TipoHoraField As SistemaServiceReference.TipoHora
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TrasladoField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Atividade() As String
            Get
                Return Me.AtividadeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AtividadeField, value) <> true) Then
                    Me.AtividadeField = value
                    Me.RaisePropertyChanged("Atividade")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Cliente() As SistemaServiceReference.Cliente
            Get
                Return Me.ClienteField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClienteField, value) <> true) Then
                    Me.ClienteField = value
                    Me.RaisePropertyChanged("Cliente")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Codigo() As Integer
            Get
                Return Me.CodigoField
            End Get
            Set
                If (Me.CodigoField.Equals(value) <> true) Then
                    Me.CodigoField = value
                    Me.RaisePropertyChanged("Codigo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Data() As Date
            Get
                Return Me.DataField
            End Get
            Set
                If (Me.DataField.Equals(value) <> true) Then
                    Me.DataField = value
                    Me.RaisePropertyChanged("Data")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Empresa() As SistemaServiceReference.Empresa
            Get
                Return Me.EmpresaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmpresaField, value) <> true) Then
                    Me.EmpresaField = value
                    Me.RaisePropertyChanged("Empresa")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Faturado() As String
            Get
                Return Me.FaturadoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FaturadoField, value) <> true) Then
                    Me.FaturadoField = value
                    Me.RaisePropertyChanged("Faturado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Filial() As SistemaServiceReference.Filial
            Get
                Return Me.FilialField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FilialField, value) <> true) Then
                    Me.FilialField = value
                    Me.RaisePropertyChanged("Filial")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Fim() As String
            Get
                Return Me.FimField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FimField, value) <> true) Then
                    Me.FimField = value
                    Me.RaisePropertyChanged("Fim")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Funcionario() As SistemaServiceReference.Funcionario
            Get
                Return Me.FuncionarioField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FuncionarioField, value) <> true) Then
                    Me.FuncionarioField = value
                    Me.RaisePropertyChanged("Funcionario")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Inicio() As String
            Get
                Return Me.InicioField
            End Get
            Set
                If (Object.ReferenceEquals(Me.InicioField, value) <> true) Then
                    Me.InicioField = value
                    Me.RaisePropertyChanged("Inicio")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Observacao() As String
            Get
                Return Me.ObservacaoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ObservacaoField, value) <> true) Then
                    Me.ObservacaoField = value
                    Me.RaisePropertyChanged("Observacao")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Projeto() As SistemaServiceReference.Projeto
            Get
                Return Me.ProjetoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ProjetoField, value) <> true) Then
                    Me.ProjetoField = value
                    Me.RaisePropertyChanged("Projeto")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Status() As SistemaServiceReference.Status
            Get
                Return Me.StatusField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StatusField, value) <> true) Then
                    Me.StatusField = value
                    Me.RaisePropertyChanged("Status")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TipoHora() As SistemaServiceReference.TipoHora
            Get
                Return Me.TipoHoraField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TipoHoraField, value) <> true) Then
                    Me.TipoHoraField = value
                    Me.RaisePropertyChanged("TipoHora")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Traslado() As String
            Get
                Return Me.TrasladoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TrasladoField, value) <> true) Then
                    Me.TrasladoField = value
                    Me.RaisePropertyChanged("Traslado")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Cliente", [Namespace]:="http://schemas.datacontract.org/2004/07/Murta.OrdemServico.Dto"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Cliente
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodigoField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NomeField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Codigo() As Integer
            Get
                Return Me.CodigoField
            End Get
            Set
                If (Me.CodigoField.Equals(value) <> true) Then
                    Me.CodigoField = value
                    Me.RaisePropertyChanged("Codigo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Nome() As String
            Get
                Return Me.NomeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NomeField, value) <> true) Then
                    Me.NomeField = value
                    Me.RaisePropertyChanged("Nome")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Empresa", [Namespace]:="http://schemas.datacontract.org/2004/07/Murta.OrdemServico.Dto"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Empresa
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodigoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NomeField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Codigo() As String
            Get
                Return Me.CodigoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodigoField, value) <> true) Then
                    Me.CodigoField = value
                    Me.RaisePropertyChanged("Codigo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Nome() As String
            Get
                Return Me.NomeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NomeField, value) <> true) Then
                    Me.NomeField = value
                    Me.RaisePropertyChanged("Nome")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Filial", [Namespace]:="http://schemas.datacontract.org/2004/07/Murta.OrdemServico.Dto"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Filial
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodigoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ReduzidoField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Codigo() As String
            Get
                Return Me.CodigoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodigoField, value) <> true) Then
                    Me.CodigoField = value
                    Me.RaisePropertyChanged("Codigo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Reduzido() As String
            Get
                Return Me.ReduzidoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ReduzidoField, value) <> true) Then
                    Me.ReduzidoField = value
                    Me.RaisePropertyChanged("Reduzido")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Funcionario", [Namespace]:="http://schemas.datacontract.org/2004/07/Murta.OrdemServico.Dto"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Funcionario
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodigoField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NomeField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Codigo() As Integer
            Get
                Return Me.CodigoField
            End Get
            Set
                If (Me.CodigoField.Equals(value) <> true) Then
                    Me.CodigoField = value
                    Me.RaisePropertyChanged("Codigo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Nome() As String
            Get
                Return Me.NomeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NomeField, value) <> true) Then
                    Me.NomeField = value
                    Me.RaisePropertyChanged("Nome")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Projeto", [Namespace]:="http://schemas.datacontract.org/2004/07/Murta.OrdemServico.Dto"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Projeto
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodigoField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DescricaoField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Codigo() As Integer
            Get
                Return Me.CodigoField
            End Get
            Set
                If (Me.CodigoField.Equals(value) <> true) Then
                    Me.CodigoField = value
                    Me.RaisePropertyChanged("Codigo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Descricao() As String
            Get
                Return Me.DescricaoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DescricaoField, value) <> true) Then
                    Me.DescricaoField = value
                    Me.RaisePropertyChanged("Descricao")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Status", [Namespace]:="http://schemas.datacontract.org/2004/07/Murta.OrdemServico.Dto"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Status
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodigoField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DescricaoField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Codigo() As Integer
            Get
                Return Me.CodigoField
            End Get
            Set
                If (Me.CodigoField.Equals(value) <> true) Then
                    Me.CodigoField = value
                    Me.RaisePropertyChanged("Codigo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Descricao() As String
            Get
                Return Me.DescricaoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DescricaoField, value) <> true) Then
                    Me.DescricaoField = value
                    Me.RaisePropertyChanged("Descricao")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="TipoHora", [Namespace]:="http://schemas.datacontract.org/2004/07/Murta.OrdemServico.Dto"),  _
     System.SerializableAttribute()>  _
    Partial Public Class TipoHora
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodigoField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DescricaoField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Codigo() As Integer
            Get
                Return Me.CodigoField
            End Get
            Set
                If (Me.CodigoField.Equals(value) <> true) Then
                    Me.CodigoField = value
                    Me.RaisePropertyChanged("Codigo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Descricao() As String
            Get
                Return Me.DescricaoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DescricaoField, value) <> true) Then
                    Me.DescricaoField = value
                    Me.RaisePropertyChanged("Descricao")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="TipoData", [Namespace]:="http://schemas.datacontract.org/2004/07/Murta.OrdemServico.Service.WCF.Enums")>  _
    Public Enum TipoData As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        DataDe = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        DataAte = 1
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="SistemaServiceReference.ISistema")>  _
    Public Interface ISistema
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISistema/CadastrarOrdemServico", ReplyAction:="http://tempuri.org/ISistema/CadastrarOrdemServicoResponse")>  _
        Sub CadastrarOrdemServico(ByVal ordemServico As SistemaServiceReference.OS)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISistema/EditarOrdemServico", ReplyAction:="http://tempuri.org/ISistema/EditarOrdemServicoResponse")>  _
        Sub EditarOrdemServico(ByVal ordemServico As SistemaServiceReference.OS)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISistema/ExcluirOrdemServico", ReplyAction:="http://tempuri.org/ISistema/ExcluirOrdemServicoResponse")>  _
        Sub ExcluirOrdemServico(ByVal ordemServico As SistemaServiceReference.OS)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISistema/ConsultarOrdemServico", ReplyAction:="http://tempuri.org/ISistema/ConsultarOrdemServicoResponse")>  _
        Function ConsultarOrdemServico(ByVal id As Integer) As SistemaServiceReference.OS
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISistema/ListarOrdemServico", ReplyAction:="http://tempuri.org/ISistema/ListarOrdemServicoResponse")>  _
        Function ListarOrdemServico() As SistemaServiceReference.OS()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISistema/ListarPorRangeDataOrdemServico", ReplyAction:="http://tempuri.org/ISistema/ListarPorRangeDataOrdemServicoResponse")>  _
        Function ListarPorRangeDataOrdemServico(ByVal dataDe As Date, ByVal dataAte As Date) As SistemaServiceReference.OS()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISistema/ListarPorRangedeDataeFuncionarioOrdemServico", ReplyAction:="http://tempuri.org/ISistema/ListarPorRangedeDataeFuncionarioOrdemServicoResponse")>  _
        Function ListarPorRangedeDataeFuncionarioOrdemServico(ByVal dataDe As Date, ByVal dataAte As Date, ByVal funcionario As SistemaServiceReference.Funcionario) As SistemaServiceReference.OS()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISistema/ListarPorRangedeDataeClienteOrdemServico", ReplyAction:="http://tempuri.org/ISistema/ListarPorRangedeDataeClienteOrdemServicoResponse")>  _
        Function ListarPorRangedeDataeClienteOrdemServico(ByVal dataDe As Date, ByVal dataAte As Date, ByVal cliente As SistemaServiceReference.Cliente) As SistemaServiceReference.OS()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISistema/ListarPorRangedeDataeFuncionarioeClienteOrdemServico", ReplyAction:="http://tempuri.org/ISistema/ListarPorRangedeDataeFuncionarioeClienteOrdemServicoR"& _ 
            "esponse")>  _
        Function ListarPorRangedeDataeFuncionarioeClienteOrdemServico(ByVal dataDe As Date, ByVal dataAte As Date, ByVal cliente As SistemaServiceReference.Cliente, ByVal funcionario As SistemaServiceReference.Funcionario) As SistemaServiceReference.OS()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISistema/ListarPorDataeFuncionarioOrdemServico", ReplyAction:="http://tempuri.org/ISistema/ListarPorDataeFuncionarioOrdemServicoResponse")>  _
        Function ListarPorDataeFuncionarioOrdemServico(ByVal data As Date, ByVal funcionario As SistemaServiceReference.Funcionario, ByVal tipo As SistemaServiceReference.TipoData) As SistemaServiceReference.OS()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISistema/ListarPorDataeClienteOrdemServico", ReplyAction:="http://tempuri.org/ISistema/ListarPorDataeClienteOrdemServicoResponse")>  _
        Function ListarPorDataeClienteOrdemServico(ByVal data As Date, ByVal cliente As SistemaServiceReference.Cliente, ByVal tipo As SistemaServiceReference.TipoData) As SistemaServiceReference.OS()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISistema/ListarPorDataeFuncionarioeClienteOrdemServico", ReplyAction:="http://tempuri.org/ISistema/ListarPorDataeFuncionarioeClienteOrdemServicoResponse"& _ 
            "")>  _
        Function ListarPorDataeFuncionarioeClienteOrdemServico(ByVal data As Date, ByVal funcionario As SistemaServiceReference.Funcionario, ByVal cliente As SistemaServiceReference.Cliente) As SistemaServiceReference.OS()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISistema/ListarPorDataOrdemServico", ReplyAction:="http://tempuri.org/ISistema/ListarPorDataOrdemServicoResponse")>  _
        Function ListarPorDataOrdemServico(ByVal data As Date, ByVal tipo As SistemaServiceReference.TipoData) As SistemaServiceReference.OS()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISistema/ListarPorFuncionarioeClienteOrdemServico", ReplyAction:="http://tempuri.org/ISistema/ListarPorFuncionarioeClienteOrdemServicoResponse")>  _
        Function ListarPorFuncionarioeClienteOrdemServico(ByVal funcionario As SistemaServiceReference.Funcionario, ByVal cliente As SistemaServiceReference.Cliente) As SistemaServiceReference.OS()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISistema/ListarPorFuncionarioOrdemServico", ReplyAction:="http://tempuri.org/ISistema/ListarPorFuncionarioOrdemServicoResponse")>  _
        Function ListarPorFuncionarioOrdemServico(ByVal funcionario As SistemaServiceReference.Funcionario) As SistemaServiceReference.OS()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISistema/ListarPorClienteOrdemServico", ReplyAction:="http://tempuri.org/ISistema/ListarPorClienteOrdemServicoResponse")>  _
        Function ListarPorClienteOrdemServico(ByVal cliente As SistemaServiceReference.Cliente) As SistemaServiceReference.OS()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISistema/ListarClientes", ReplyAction:="http://tempuri.org/ISistema/ListarClientesResponse")>  _
        Function ListarClientes() As SistemaServiceReference.Cliente()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISistema/ListarProjetos", ReplyAction:="http://tempuri.org/ISistema/ListarProjetosResponse")>  _
        Function ListarProjetos() As SistemaServiceReference.Projeto()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISistema/ListarTiposHora", ReplyAction:="http://tempuri.org/ISistema/ListarTiposHoraResponse")>  _
        Function ListarTiposHora() As SistemaServiceReference.TipoHora()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISistema/ListarFuncionarios", ReplyAction:="http://tempuri.org/ISistema/ListarFuncionariosResponse")>  _
        Function ListarFuncionarios() As SistemaServiceReference.Funcionario()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISistema/ListarStatus", ReplyAction:="http://tempuri.org/ISistema/ListarStatusResponse")>  _
        Function ListarStatus() As SistemaServiceReference.Status()
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ISistemaChannel
        Inherits SistemaServiceReference.ISistema, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class SistemaClient
        Inherits System.ServiceModel.ClientBase(Of SistemaServiceReference.ISistema)
        Implements SistemaServiceReference.ISistema
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Sub CadastrarOrdemServico(ByVal ordemServico As SistemaServiceReference.OS) Implements SistemaServiceReference.ISistema.CadastrarOrdemServico
            MyBase.Channel.CadastrarOrdemServico(ordemServico)
        End Sub
        
        Public Sub EditarOrdemServico(ByVal ordemServico As SistemaServiceReference.OS) Implements SistemaServiceReference.ISistema.EditarOrdemServico
            MyBase.Channel.EditarOrdemServico(ordemServico)
        End Sub
        
        Public Sub ExcluirOrdemServico(ByVal ordemServico As SistemaServiceReference.OS) Implements SistemaServiceReference.ISistema.ExcluirOrdemServico
            MyBase.Channel.ExcluirOrdemServico(ordemServico)
        End Sub
        
        Public Function ConsultarOrdemServico(ByVal id As Integer) As SistemaServiceReference.OS Implements SistemaServiceReference.ISistema.ConsultarOrdemServico
            Return MyBase.Channel.ConsultarOrdemServico(id)
        End Function
        
        Public Function ListarOrdemServico() As SistemaServiceReference.OS() Implements SistemaServiceReference.ISistema.ListarOrdemServico
            Return MyBase.Channel.ListarOrdemServico
        End Function
        
        Public Function ListarPorRangeDataOrdemServico(ByVal dataDe As Date, ByVal dataAte As Date) As SistemaServiceReference.OS() Implements SistemaServiceReference.ISistema.ListarPorRangeDataOrdemServico
            Return MyBase.Channel.ListarPorRangeDataOrdemServico(dataDe, dataAte)
        End Function
        
        Public Function ListarPorRangedeDataeFuncionarioOrdemServico(ByVal dataDe As Date, ByVal dataAte As Date, ByVal funcionario As SistemaServiceReference.Funcionario) As SistemaServiceReference.OS() Implements SistemaServiceReference.ISistema.ListarPorRangedeDataeFuncionarioOrdemServico
            Return MyBase.Channel.ListarPorRangedeDataeFuncionarioOrdemServico(dataDe, dataAte, funcionario)
        End Function
        
        Public Function ListarPorRangedeDataeClienteOrdemServico(ByVal dataDe As Date, ByVal dataAte As Date, ByVal cliente As SistemaServiceReference.Cliente) As SistemaServiceReference.OS() Implements SistemaServiceReference.ISistema.ListarPorRangedeDataeClienteOrdemServico
            Return MyBase.Channel.ListarPorRangedeDataeClienteOrdemServico(dataDe, dataAte, cliente)
        End Function
        
        Public Function ListarPorRangedeDataeFuncionarioeClienteOrdemServico(ByVal dataDe As Date, ByVal dataAte As Date, ByVal cliente As SistemaServiceReference.Cliente, ByVal funcionario As SistemaServiceReference.Funcionario) As SistemaServiceReference.OS() Implements SistemaServiceReference.ISistema.ListarPorRangedeDataeFuncionarioeClienteOrdemServico
            Return MyBase.Channel.ListarPorRangedeDataeFuncionarioeClienteOrdemServico(dataDe, dataAte, cliente, funcionario)
        End Function
        
        Public Function ListarPorDataeFuncionarioOrdemServico(ByVal data As Date, ByVal funcionario As SistemaServiceReference.Funcionario, ByVal tipo As SistemaServiceReference.TipoData) As SistemaServiceReference.OS() Implements SistemaServiceReference.ISistema.ListarPorDataeFuncionarioOrdemServico
            Return MyBase.Channel.ListarPorDataeFuncionarioOrdemServico(data, funcionario, tipo)
        End Function
        
        Public Function ListarPorDataeClienteOrdemServico(ByVal data As Date, ByVal cliente As SistemaServiceReference.Cliente, ByVal tipo As SistemaServiceReference.TipoData) As SistemaServiceReference.OS() Implements SistemaServiceReference.ISistema.ListarPorDataeClienteOrdemServico
            Return MyBase.Channel.ListarPorDataeClienteOrdemServico(data, cliente, tipo)
        End Function
        
        Public Function ListarPorDataeFuncionarioeClienteOrdemServico(ByVal data As Date, ByVal funcionario As SistemaServiceReference.Funcionario, ByVal cliente As SistemaServiceReference.Cliente) As SistemaServiceReference.OS() Implements SistemaServiceReference.ISistema.ListarPorDataeFuncionarioeClienteOrdemServico
            Return MyBase.Channel.ListarPorDataeFuncionarioeClienteOrdemServico(data, funcionario, cliente)
        End Function
        
        Public Function ListarPorDataOrdemServico(ByVal data As Date, ByVal tipo As SistemaServiceReference.TipoData) As SistemaServiceReference.OS() Implements SistemaServiceReference.ISistema.ListarPorDataOrdemServico
            Return MyBase.Channel.ListarPorDataOrdemServico(data, tipo)
        End Function
        
        Public Function ListarPorFuncionarioeClienteOrdemServico(ByVal funcionario As SistemaServiceReference.Funcionario, ByVal cliente As SistemaServiceReference.Cliente) As SistemaServiceReference.OS() Implements SistemaServiceReference.ISistema.ListarPorFuncionarioeClienteOrdemServico
            Return MyBase.Channel.ListarPorFuncionarioeClienteOrdemServico(funcionario, cliente)
        End Function
        
        Public Function ListarPorFuncionarioOrdemServico(ByVal funcionario As SistemaServiceReference.Funcionario) As SistemaServiceReference.OS() Implements SistemaServiceReference.ISistema.ListarPorFuncionarioOrdemServico
            Return MyBase.Channel.ListarPorFuncionarioOrdemServico(funcionario)
        End Function
        
        Public Function ListarPorClienteOrdemServico(ByVal cliente As SistemaServiceReference.Cliente) As SistemaServiceReference.OS() Implements SistemaServiceReference.ISistema.ListarPorClienteOrdemServico
            Return MyBase.Channel.ListarPorClienteOrdemServico(cliente)
        End Function
        
        Public Function ListarClientes() As SistemaServiceReference.Cliente() Implements SistemaServiceReference.ISistema.ListarClientes
            Return MyBase.Channel.ListarClientes
        End Function
        
        Public Function ListarProjetos() As SistemaServiceReference.Projeto() Implements SistemaServiceReference.ISistema.ListarProjetos
            Return MyBase.Channel.ListarProjetos
        End Function
        
        Public Function ListarTiposHora() As SistemaServiceReference.TipoHora() Implements SistemaServiceReference.ISistema.ListarTiposHora
            Return MyBase.Channel.ListarTiposHora
        End Function
        
        Public Function ListarFuncionarios() As SistemaServiceReference.Funcionario() Implements SistemaServiceReference.ISistema.ListarFuncionarios
            Return MyBase.Channel.ListarFuncionarios
        End Function
        
        Public Function ListarStatus() As SistemaServiceReference.Status() Implements SistemaServiceReference.ISistema.ListarStatus
            Return MyBase.Channel.ListarStatus
        End Function
    End Class
End Namespace
